---
title: "Health effects of research and implementation decisions"
params:
  Cell_A: NA
  Cell_C: NA
  Cell_D: NA
  ICER_ResearchWithCurrentImplementation: NA
  ICER_ResearchWithPerfectImplementation: NA
  absoluteExpectedHealthOutcomesFromResearchProject: NA
  expectedCostHealthSystem: NA
  expectedCostResearchFunder: NA
  expectedOutcomesPerYearoptimalTreatment: NA
  healthOpportunityCostsOfResearch: NA
  implementationValueExists: NA
  listForhistVOIYear: NA
  maxvalueOfImplementation: NA
  maxvalueOfResearch: NA
  optimalTreatment: NA
  popAfterDefinitiveResearch: NA
  popAfterResearch: NA
  popDuringDefinitiveResearch: NA
  popDuringFeasResearch: NA
  popDuringResearch: NA
  popTotal: NA
  probOptimalTisMax: NA
  probOptimalTisNotMax: NA
  probTreatment1isMax: NA
  probTreatment2isMax: NA
  probTreatment3isMax: NA
  probTreatment4isMax: NA
  tableEventsPerYearDF: NA
  tableProbabilityMaxDF: NA
  tableTreatmentCostsDF: NA
  uncertaintyInCurrentEvidenceExists: NA
  valueOfCertainResearchWithPerfectImplementation: NA
  valueOfImplementationPerYear: NA
  valueOfResearchPerYear: NA
  valueOfResearchWithCurrentImplementation: NA
  valueOfResearchWithPerfectImplementation: NA
  valuePer15KResearchSpend: NA
  valuePerOpCostResearchSpend: NA
output:
  html_document: default
  word_document: default
---

<!---
Each code chunk either evaluates or it does not, depending on whehter eval = TRUE
To evaluate a chunk if a result is FALSE use eval = !params$nameofobject
**the space after eval = is very important otherwise it confuses markdown.


FormatExpectedCostResearchFunder : NA
-->

<!-- # ```{r results='hide',message=FALSE   } -->
<!-- #  -->
<!-- # PositiveValueOfInformation <- params$maxvalueOfResearch > 0 -->
<!-- #  -->
<!-- # ``` -->

See code below - can do boolean phrases directly in eval argument - easier than in Shiny

```{r conditional_blockn, echo=FALSE, results='asis', eval= params$maxvalueOfResearch > 0}
cat("* There is value in research!
    
    ")
```



## Headline Results

```{r conditional_block, echo=FALSE, results='asis', eval=TRUE}
cat("* Given what we currently know about the treatments, the option with the highest expected health benefit is", params$optimalTreatment, "with 3,101 functional recoverys per year.
    
    ")
```



```{r conditional_block2, echo=FALSE, results='asis', eval= params$implementationValueExists}
cat("will display if params$implementationValueExist = TRUE
    ")
```


```{r conditional_block3, echo=FALSE, results='asis', eval= !params$implementationValueExists}
cat("will display if params$implementationValueExist = FALSE (turns a false into true)
    ")
```





```{r}
# The `params` object is available in the document.
# NB: when adding objects to params list - must set default value in report.Rmd equal to NA
#params$n
```



```{r}
#plot(rnorm(params$n), rnorm(params$n))
```

`r if(params$implementationValueExists){"there is imp value"}`

`r if(!params$implementationValueExists){"there is NO imp value"}`

`r if(TRUE){"#Header\nIs this under the header\n\n##subheader\nis this undersub?"}`



```{r}

if(params$implementationValueExists){
  "there is imp value"
  
  }

if(!params$implementationValueExists){
  "there is NO imp value"
  
  }

```


```{r}


params$FormatExpectedCostResearchFunder
params$optimalTreatment
params$probTreatment1isMax
params$probTreatment2isMax
params$probTreatment3isMax 
params$probTreatment4isMax 
params$implementationValueExists 
params$uncertaintyInCurrentEvidenceExists 
params$listForhistVOIYear 
params$valueOfResearchPerYear 
params$tableEventsPerYearDF         
params$tableProbabilityMaxDF 
params$tableTreatmentCostsDF 
params$healthOpportunityCostsOfResearch 
params$ICER_ResearchWithCurrentImplementation
params$ICER_ResearchWithPerfectImplementation 
params$popAfterDefinitiveResearch 
params$expectedCostResearchFunder     
params$expectedCostHealthSystem  
params$valueOfCertainResearchWithPerfectImplementation

if(params$uncertaintyInCurrentEvidenceExists == TRUE){
  "There is uncertainty in decision"
} else {
  "there is no uncertainty in decision"
}


```








