###
# P6
####


source("W:/teehta/David G/ShinyApps/RShinyVOI/ShinyFiles/SupplementaryFunctions.R", local = TRUE)
source("W:/teehta/David G/ShinyApps/RShinyVOI/ShinyFiles/SupplementaryFunctionsFeas.R", local = TRUE)
source("W:/teehta/David G/ShinyApps/RShinyVOI/ShinyFiles/master.R", local = TRUE)
source("W:/teehta/David G/ShinyApps/RShinyVOI/ShinyFiles/ReconFunctions.R", local = TRUE)
source("W:/teehta/David G/ShinyApps/RShinyVOI/ShinyFiles/EpiInputFunctions.R", local = TRUE)
source("W:/teehta/David G/ShinyApps/RShinyVOI/ShinyFiles/PlottingFunctions.R", local = TRUE)
source("W:/teehta/David G/ShinyApps/RShinyVOI/ShinyFiles/EpiCalcFunctions.R", local = TRUE)
source("W:/teehta/David G/ShinyApps/RShinyVOI/ShinyFiles/NBCalcFunctions.R", local = TRUE)

# home WD
setwd("C:/Users/David/Desktop/Work/R files/Shiny/Tool/ShinyFiles")
source("SupplementaryFunctions.R", local = TRUE)
source("SupplementaryFunctionsFeas.R", local = TRUE)
source("master.R", local = TRUE)
source("ReconFunctions.R", local = TRUE)
source("EpiInputFunctions.R", local = TRUE)
source("PlottingFunctions.R", local = TRUE)
source("EpiCalcFunctions.R", local = TRUE)
source("NBCalcFunctions.R", local = TRUE)



# need to put in proper values


# Natural outcome
####################################
master(
  typeOfEndpoint = "binary", # 'binary', "continuous''survival"
  baselineInput = "range", # "eventsNonEvents" "range"
  MCsims = 900000,
  baselineRange = c(0.05, 0.06) ,
  nEvents = NA,
  nAtRisk = NA,
  numberOfTreatments = 2,
  binaryRelativeScale_t2 = "OR",
  binaryRelativeScale_t3 = NA,
  binaryRelativeScale_t4 = NA,
  binaryDist_t2 = "norm",
  binaryDist_t3 = NA ,
  binaryDist_t4 = NA,
  OR_t2= c(0.19 , 4.39),
  OR_t3 = NA,
  OR_t4= NA,
  RR_t2 =NA,
  RR_t3 =NA,
  RR_t4 =NA,
  RD_t2 =NA,
  RD_t3=NA,
  RD_t4=NA,
  ORHalfNorm_t2=NA,
  ORHalfNorm_t3=NA,
  ORHalfNorm_t4=NA,
  RRHalfNorm_t2=NA,
  RRHalfNorm_t3=NA,
  RRHalfNorm_t4=NA,
  RDHalfNorm_t2=NA,
  RDHalfNorm_t3=NA,
  RDHalfNorm_t4=NA,
  continuousInput_t2=NA, # "range", # "meanAndSE",
  continuousInput_t3=NA ,# "meanAndSE",
  continuousInput_t4=NA, # "meanAndSE",
  continMean_t2=NA,
  continMean_t3=NA,
  continMean_t4=NA,
  continSE_t2=NA,
  continSE_t3=NA,
  continSE_t4=NA,
  continDist_t2=NA, #  "alwaysNegative"  "norm",
  continDist_t3=NA, #  "alwaysNegative"  "norm",
  continDist_t4=NA, #  "alwaysNegative"  "norm",
  MD_t2=NA,
  MD_t3=NA,
  MD_t4=NA,
  MDHalfNorm_t2=NA,
  MDHalfNorm_t3=NA,
  MDHalfNorm_t4=NA,
  survivalType = NA, # "exponential", # "weibull",
  survivalDist_t2=NA ,#  "alwaysNegative"  "norm",,"alwaysPositive" 
  survivalDist_t3=NA, #  "alwaysNegative"  "norm",,"alwaysPositive" 
  survivalDist_t4=NA ,#  "alwaysNegative"  "norm",,
  lambda_t1= NA ,
  gamma_t1=NA,
  HR_t2=NA,
  HR_t3=NA,
  HR_t4=NA,
  HRHalfNorm_t2=NA,
  HRHalfNorm_t3=NA,
  HRHalfNorm_t4=NA,
  typeOfOutcome= "harm", # "benefit" or "harm" "netHealth"
  tCostsDependOnEvent= NA,
  MCD_t2 = 0.0,
  MCD_t3 = NA,
  MCD_t4 = NA,
  cost_t1 = NA ,
  cost_t2= NA,
  cost_t3 = NA,
  cost_t4 = NA,
  k = NA,
  currencySymbol = "£",
  incidence = 26.3 ,
  discountRate = 3.5 , # NB - this is how ui provides the discount rate!
  timeInformation = 10,
  nameOf_t1 = "Continuous treatment",
  nameOf_t2 = "Withdrawal",
  nameOf_t3 = NA,
  nameOf_t4 = NA,
  costEvent_t1 = NA,
  costEvent_t2 = NA,
  costEvent_t3 = NA,
  costEvent_t4 = NA,
  costNotEvent_t1 = NA,
  costNotEvent_t2 = NA,
  costNotEvent_t3 = NA,
  costNotEvent_t4 = NA,
  numberS0States = NA, # if event does not occur
  numberS1States = NA , # if event occurs
  utility_s01 = NA, # if recovery does not occur
  utility_s02 = NA,
  utility_s03 = NA,
  utility_s04 = NA,
  utility_s11 = NA, # recovery does occur
  utility_s12 = NA,
  utility_s13 = NA,
  utility_s14 = NA,
  lifeDuration_s01 = NA, #if recovery does not occur
  lifeDuration_s02 = NA,
  lifeDuration_s03 = NA,
  lifeDuration_s04 = NA,
  lifeDuration_s11 = NA, # recovery does occur
  lifeDuration_s12 = NA,
  lifeDuration_s13 = NA,
  lifeDuration_s14 = NA,
  cost_s01 = NA,   #if recovery does not occur
  cost_s02 = NA,
  cost_s03 = NA,
  cost_s04 = NA,
  cost_s11 = NA, # recovery does occur
  cost_s12 = NA,
  cost_s13 = NA,
  cost_s14 = NA,
  probability_s01 = NA, #if recovery does not occur
  probability_s02 = NA,
  probability_s03 = NA,
  probability_s04 = NA,
  probability_s11 = NA, # recovery does occur
  probability_s12 = NA,
  probability_s13 = NA,
  probability_s14 = NA,
  deltaUnitUtilityDirection = NA, # "increase" # Q Is an increase in the primary outcome expected to be associated with an increase or decrease in health state utility?
  deltaUnitUtilitySize = NA, # Q By how much is a one unit increase in the primary outcome expected to increase/decrease the health state utility?
  treatmentDurationMonths = NA, # Q how long is the treatment effect expected to last
  deltaUnitCostsDirection = NA, # "increase" # Q Is an increase in the primary outcome expected to be associated with disease related cost increases or decreases?
  deltaUnitCostsSize = NA, # Q By how much is a one unit increase in the primary outcome expected to increase/decrease disease related costs?
  treatmentCostsMonthly_t1 = NA, # used in survival too
  treatmentCostsMonthly_t2 = NA,# used in survival too
  treatmentCostsMonthly_t3 = NA,# used in survival too
  treatmentCostsMonthly_t4 = NA,# used in survival too
  utilityPreTransition = NA, # Q What is the health utility associated with the pre-progression health state?
  monthlyCostPreTransition = NA, # Q What are the expected monthly disease related costs associated with the pre-transition health state?
  treatUntilProgression_t1 = NA, # "No"  Q Are individuals always treated until progression under the baseline treatment?
  maxDurationOfTreatmentMonths_t1 = NA, # Q what is the maximum number of months that the baseline treatment will be given?
  treatUntilProgression_t2 = NA, # "No" "Yes"
  maxDurationOfTreatmentMonths_t2 = NA,
  treatUntilProgression_t3 = NA, # "No" "Yes"
  maxDurationOfTreatmentMonths_t3 = NA,
  treatUntilProgression_t4 = NA, # "No" "Yes"
  maxDurationOfTreatmentMonths_t4 = NA,
  typeOfResearch = "RCT", # "RCT",  # "feasibility",
  durationOfResearch = 4,
  costResearchFunder = 855403,
  utilisation_t1 = 100,
  utilisation_t2 = 0,
  utilisation_t3 = NA,
  utilisation_t4 = NA,
  costHealthSystem = NA,
  durationOfResearchDefinitive = NA,
  durationOfResearchFeas = NA,
  costResearchFunderFeas = NA,
  costResearchFunderDefinitive =  NA,
  probabilityOfDefinitiveResearch = NA,
  costHealthSystemFeas = NA,
  costHealthSystemDefinitive = NA
)








# costs and QALYs
####################################
master(
  typeOfEndpoint = "binary", # 'binary', "continuous''survival"
  baselineInput = "range", # "eventsNonEvents" "range"
  MCsims = 900000,
  baselineRange = c(0.05, 0.06) ,
  nEvents = NA,
  nAtRisk = NA,
  numberOfTreatments = 2,
  binaryRelativeScale_t2 = "OR",
  binaryRelativeScale_t3 = NA,
  binaryRelativeScale_t4 = NA,
  binaryDist_t2 = "norm",
  binaryDist_t3 = NA ,
  binaryDist_t4 = NA,
  OR_t2= c(0.19 , 4.39),
  OR_t3 = NA,
  OR_t4= NA,
  RR_t2 =NA,
  RR_t3 =NA,
  RR_t4 =NA,
  RD_t2 =NA,
  RD_t3=NA,
  RD_t4=NA,
  ORHalfNorm_t2=NA,
  ORHalfNorm_t3=NA,
  ORHalfNorm_t4=NA,
  RRHalfNorm_t2=NA,
  RRHalfNorm_t3=NA,
  RRHalfNorm_t4=NA,
  RDHalfNorm_t2=NA,
  RDHalfNorm_t3=NA,
  RDHalfNorm_t4=NA,
  continuousInput_t2=NA, # "range", # "meanAndSE",
  continuousInput_t3=NA ,# "meanAndSE",
  continuousInput_t4=NA, # "meanAndSE",
  continMean_t2=NA,
  continMean_t3=NA,
  continMean_t4=NA,
  continSE_t2=NA,
  continSE_t3=NA,
  continSE_t4=NA,
  continDist_t2=NA, #  "alwaysNegative"  "norm",
  continDist_t3=NA, #  "alwaysNegative"  "norm",
  continDist_t4=NA, #  "alwaysNegative"  "norm",
  MD_t2=NA,
  MD_t3=NA,
  MD_t4=NA,
  MDHalfNorm_t2=NA,
  MDHalfNorm_t3=NA,
  MDHalfNorm_t4=NA,
  survivalType = NA, # "exponential", # "weibull",
  survivalDist_t2=NA ,#  "alwaysNegative"  "norm",,"alwaysPositive" 
  survivalDist_t3=NA, #  "alwaysNegative"  "norm",,"alwaysPositive" 
  survivalDist_t4=NA ,#  "alwaysNegative"  "norm",,
  lambda_t1= NA ,
  gamma_t1=NA,
  HR_t2=NA,
  HR_t3=NA,
  HR_t4=NA,
  HRHalfNorm_t2=NA,
  HRHalfNorm_t3=NA,
  HRHalfNorm_t4=NA,
  typeOfOutcome= "netHealth", # "benefit" or "harm" "netHealth"
  tCostsDependOnEvent= "Yes",
  MCD_t2 = 0.0,
  MCD_t3 = NA,
  MCD_t4 = NA,
  cost_t1 = NA ,
  cost_t2= NA,
  cost_t3 = NA,
  cost_t4 = NA,
  k = 15000,
  currencySymbol = "£",
  incidence = 26.3 ,
  discountRate = 3.5 , # NB - this is how ui provides the discount rate!
  timeInformation = 10,
  nameOf_t1 = "Continuous treatment",
  nameOf_t2 = "Withdrawal",
  nameOf_t3 = NA,
  nameOf_t4 = NA,
  costEvent_t1 = , # relapse occurs
  costEvent_t2 = ,
  costEvent_t3 = NA,
  costEvent_t4 = NA,
  costNotEvent_t1 = , # relapse does not occur
  costNotEvent_t2 = ,
  costNotEvent_t3 = NA,
  costNotEvent_t4 = NA,
  numberS0States = 1, # if event does not occur
  numberS1States = 3 , # if event occurs
  utility_s01 = NA, # if recovery does not occur
  utility_s02 = NA,
  utility_s03 = NA,
  utility_s04 = NA,
  utility_s11 = NA, # recovery does occur
  utility_s12 = NA,
  utility_s13 = NA,
  utility_s14 = NA,
  lifeDuration_s01 = NA, #if recovery does not occur
  lifeDuration_s02 = NA,
  lifeDuration_s03 = NA,
  lifeDuration_s04 = NA,
  lifeDuration_s11 = NA, # recovery does occur
  lifeDuration_s12 = NA,
  lifeDuration_s13 = NA,
  lifeDuration_s14 = NA,
  cost_s01 = NA,   #if recovery does not occur
  cost_s02 = NA,
  cost_s03 = NA,
  cost_s04 = NA,
  cost_s11 = NA, # recovery does occur
  cost_s12 = NA,
  cost_s13 = NA,
  cost_s14 = NA,
  probability_s01 = NA, #if recovery does not occur
  probability_s02 = NA,
  probability_s03 = NA,
  probability_s04 = NA,
  probability_s11 = NA, # recovery does occur
  probability_s12 = NA,
  probability_s13 = NA,
  probability_s14 = NA,
  deltaUnitUtilityDirection = NA, # "increase" # Q Is an increase in the primary outcome expected to be associated with an increase or decrease in health state utility?
  deltaUnitUtilitySize = NA, # Q By how much is a one unit increase in the primary outcome expected to increase/decrease the health state utility?
  treatmentDurationMonths = NA, # Q how long is the treatment effect expected to last
  deltaUnitCostsDirection = NA, # "increase" # Q Is an increase in the primary outcome expected to be associated with disease related cost increases or decreases?
  deltaUnitCostsSize = NA, # Q By how much is a one unit increase in the primary outcome expected to increase/decrease disease related costs?
  treatmentCostsMonthly_t1 = NA, # used in survival too
  treatmentCostsMonthly_t2 = NA,# used in survival too
  treatmentCostsMonthly_t3 = NA,# used in survival too
  treatmentCostsMonthly_t4 = NA,# used in survival too
  utilityPreTransition = NA, # Q What is the health utility associated with the pre-progression health state?
  monthlyCostPreTransition = NA, # Q What are the expected monthly disease related costs associated with the pre-transition health state?
  treatUntilProgression_t1 = NA, # "No"  Q Are individuals always treated until progression under the baseline treatment?
  maxDurationOfTreatmentMonths_t1 = NA, # Q what is the maximum number of months that the baseline treatment will be given?
  treatUntilProgression_t2 = NA, # "No" "Yes"
  maxDurationOfTreatmentMonths_t2 = NA,
  treatUntilProgression_t3 = NA, # "No" "Yes"
  maxDurationOfTreatmentMonths_t3 = NA,
  treatUntilProgression_t4 = NA, # "No" "Yes"
  maxDurationOfTreatmentMonths_t4 = NA,
  typeOfResearch = "RCT", # "RCT",  # "feasibility",
  durationOfResearch = 4,
  costResearchFunder = 855403,
  utilisation_t1 = 100,
  utilisation_t2 = 0,
  utilisation_t3 = NA,
  utilisation_t4 = NA,
  costHealthSystem = NA,
  durationOfResearchDefinitive = NA,
  durationOfResearchFeas = NA,
  costResearchFunderFeas = NA,
  costResearchFunderDefinitive =  NA,
  probabilityOfDefinitiveResearch = NA,
  costHealthSystemFeas = NA,
  costHealthSystemDefinitive = NA
)

